image: alpine/edge
packages:
  - shellcheck
  - editorconfig-checker
sources:
  - https://git.sr.ht/~mil/sxmo-utils
tasks:
  - shellcheck: |
      cd sxmo-utils
      shellcheck scripts/*/*
  - editorconfig-check: |
      cd sxmo-utils
      ec
